### ISSUE TITLE
Przechowywanie kopii stref w plikach

### ISSUE THREAD

**Issue by mrwogu** [DevelopersPL/godnsagent#1]
Obecnie:
Po restarcie usługi - wszystkie strefy ładowane są z API do pamięci.
W przypadku braku odpowiedzi z API - godnsagent nie serwuje kompletnie nic.

Można by przechowywać kopię stref w plikach, które zostaną nadpisane tylko w przypadku gdy odpowiedź z API jest poprawna.

**Comment by DSpeichert** [comment]
Fixed in 90e9f009cf678031c9edad7b57d045524b77c9d2
